version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"

  web:
    build: .
    command: python app.py
    volumes:
      - .:/app
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - NAME=World
      - DATABASE_URL=postgresql://username:password@localhost:5432/dbname  # Update with your actual database credentials